---
title: "article 2 :What drove Japan to re-start barbaric commercial whale hunting after 30 years"
description: |
  This article is about whaling in Japan.
author:
  - name: Joffrey Thulier
    url: {}
date: 11-01-2019
preview: image/baleine1.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## I. Title of the article: 

What drove Japan to re-start barbaric commercial whale hunting after 30 years.

## II. Name of the Magazine + Source [URL]:

Mirror: <https://www.mirror.co.uk/news/world-news/what-drove-japan-re-start-17720163>

author: Rhian Lubin


##  III. Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| fierce | ferocious |
| carryout| make/effect |
| to try | to test |
| allow | authorize |
| sustainable | lasting/durable |
| pull out | extract |
| argue | protect |
| coast | seaboard |
| to increase | to augment |
| *minke*, *Bryde's*, *Sei whales* | wahale species |
| carbon footprint | scientific measurement |
| to bind | to link / to join |
| law | what is legal |
| appal | alarm / to horrify |
| within | inside |
| to the fore | give prominenece to |
| renegade | outlaw |
| undermine | diminish |
| plummet | drop |
| bleak | dark |

## IV. Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  |  >Steve Backshall: Naturalist and TV present. >Kitty Block: president of Humane Society International. >Dominic Dyer of Born Free Foundation
| Published in?                | 08/10/2019                                                       |
| General topic?               | Japan leaves the IWC because they refuse permission whale hunting.despite the many opposition and where the atmosphere is more to the protection of the environment. |
| Procedure/what was examined? |  interview. observation of fishermen and decisions of the Japanese government |
| Conclusions/discovery?       | Leaving IWC, Japan resumes commercial whaling but Japan never really stopped whaling.Japan is allowed to hunt minke, Bryde's and sei whales, only in its economic zone.In the late 1940s to the mid 1960s whale was the biggest source of meat in the country but since consumption to fall by 99%.        |
| Remaining questions?         | (/) |



