---
title: "article-8"
description: |
  A short description of the post.
author:
  - name: Joffrey Thulier
    url: {}
date: 03-21-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## I. Title of the article: 

Endangered Blue Whales Make 'Unprecedented' Comeback to South Georgia Island

## II. Name of the Magazine + Source [URL]:

EcoWatch : <https://www.ecowatch.com/endangered-blue-whales-comeback-2645234395.html?rebelltitem=3#rebelltitem3>

author:  Olivia Rosane


##  III. Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| fiel | land |
| astonishing | amazing |
| thrilled | excited |
| seal | marine mammal |
| trend | tendency |
| assessment | evaluation | 


## IV. Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  |  Trevor Branch: doctor at the University of Washington |
| Published in?                | 02/24/20 |
| General topic?               |  the researchers discovered a feeding place for whales on the  sub-Antarctic island of south georgia. This place was an important hunting place in the first half of the 20th century. In 1986, it became a protected place and now, 30 years later, whales return in large numbers. |
| Procedure/what was examined? |  observe and count the number of whales. |
| Conclusions/discovery?       |  CBI researchers must carry out a study to confirm the return of the whales  |
| Remaining questions?         |  (/) |

