---
title: "article-5"
description: |
  A short description of the post.
author:
  - name: Joffrey Thulier
    url: {}
date: 12-11-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## I. Title of the article: 

Besides Japan, Other Countries Continue to Hunt Whales

## II. Name of the Magazine + Source [URL]:

U.S.News : <https://www.usnews.com/news/best-countries/articles/2019-07-05/besides-japan-other-countries-continue-to-hunt-whales?fbclid=IwAR0_aaF2MoHsy_D78zpxeE9cgu0-5yaxjK8sbHCvqT5DWuaC9F1wlDN0Uuo>

author: Lauren Favre


##  III. Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| earlier | before |
| bring | take |
| catch | fishing/hunting |
| withdraw | retreat |
| spite | after |
| still | again |
| within | on the inside off |
| thing | aspects |
| enough | sufficiently |
| way | manner |
| pregnant | carrying a foetus |
| solely | only |
| tell | inform |
| fewer | less |

## IV. Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Kitty Block: President of Humane Society International.|
| Published in?                | 07/05/2019                       |
| General topic?               |  Japan is not the only country to hunt whales. There is also Norway and Iceland|
| Conclusions/discovery?       |   Japan is not the only country to hunt whales. There is also Norway and Iceland either under objection to the moratorium decision, or under reservation to it.The Russian Federation has also objected to the moratorium, but has not proceeded to resume whaling.Japan hunts for Sei whales, they are classified as endangered.The IWC sets catch limits for commercial whaling in international seas, the organization currently has 88 members.en quittant le IWC, le japon have been seeing son quota de baleine diminué.     |
| Remaining questions?         | (/) |


