---
title: "article 1: Japan begins whaling after 30 years of peace"
description: |
  This article is about whaling in Japan.
author: 
  - name: "Joffrey Thulier"
    url: {}
date: 10-21-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## I. Title of the article: 

Japan begins whaling after 30 years of peace

## II. Name of the Magazine + Source [URL]:

Sonoma State Star: <http://www.sonomastatestar.com/opinion/2019/9/17/japan-begins-whaling-after-30-years-of-peace>

author: Leah Magnuson


##  III. Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| although   | despite                   |
| fleet| boat set         |
| intent |plan |
| to allow | to permit |
| old ways | habit |
| to grow | to accrue |
| fading away | fade out |
| disgust | aversion/nausea |
| overwhelming | crushing |
| slaughtering | killing |
| to hoist | to elevate |
| crane | vehicle to lift |
| to bring | to guide/to lead |
| to agrue | to argument |
| scarcity | insufficiency |
| to provide | to procure |
| flesh | meat |
| taste | savour |
| to state | to declare |
| quote | citation |
| welfare | comfort |
| palate | taste ( upper part off the mouth )
| to hope | wish |
| to avoid | to evade |
| obsolete | outdated |
| to occur | to come about |
| worrisome | unreassuring |


### text: 

Japan begins whaling after 30 years of peace.

**Although** there has not been a commercial whale hunt since 1986, on July 1st, a **fleet** was sent out with the **intent** to kill. This change shocked citizens since Japan left the International Whaling Commission last year that does not **allow** the hunting of whales. This whaling ban was put in place to allow the whale population to recover and **grow**, according to environmental organization Greenpeace. However, even though the last hunt occurred over 30 years ago, Japan seems to be going back to its **old ways**.

Japan’s decision to begin whaling commercially again is an attempt to revive the whaling industry, which was once booming, but is now **fading away**. This has caused international **disgust** as well as an **overwhelming** feeling of disappointment by activists, political leaders and citizens alike. The **slaughtering** of whales is carried out by impaling them repeatedly until they bleed out in the water before being **hoisted** by **crane** onto the boat. The process of doing so is barbaric and inhumane, and could seriously damage whale populations, especially if other countries lead by example.

Whaling will once again take place for these majestic creatures that have almost been **brought** to the point of extinction because of being hunted by humans. BBC News stated that Japan has **argued** that hunting and consuming whales is part of their culture. Many countries alike have different traditions than western culture that can seem violent in nature, even though it’s normal to those people. It is true that whales have been hunted by different communities for centuries, but that was out of necessity because of **scarcity** and limited availability of food. Whaling was once needed to **provide** an essential protein source, but it is no longer necessary. It is now being used in an attempt to try to revive a dying industry for the quest of big profit, even if the ultimate cost is the extinction of this species. 

The **taste** of whale **flesh** has been desired less and less, and many believe that this will not bring this industry back to life. An article posted by The Guardian **stated** a **quote** by Patrick Ramage, director of marine conservation at the International Fund for Animal **Welfare**; “The **palates** of the Japanese people have moved on.” Many are **hoping** that japanese people will also protest this barbaric practice and not support killing whales, by **avoiding** buying whale meat and other products. 

Ramage explains that the practice is not conventional or desired, and that it will eventually burn itself out. “What we are seeing is the beginning of the end of Japanese whaling.” There is hope that whaling will once again become **obsolete**, but the slaughtering that is **occurring** in the meantime is **worrisome** as well as potentially catastrophic for the whale population. Many activist groups have decided to take a step back, but the future for our oceans and those that live in it is uncertain. 



## IV. Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Patrick Ramage, director of marine conservation at the International Fund for Animal Welfare           |
| Published in?                | 09/17/2019                                                       |
| General topic?               | Japan throwed whaling again for commercial pruposes while the meat trade is declining.|
| Procedure/what was examined? | archive seach, interview,resume and read from other magazines(BBC, The Guardian) and fact finding. |
| Conclusions/discovery?       |  The way whales are killed discourages the Japanese from buying this meat.There is hope that whaling will wipe from Japanese customs thanks to low demand and that its trade vanish.      |
| Remaining questions?         | (/) |

